arrowParens: always # 箭头函数参数使用括号
bracketSpacing: true # 对象字面量的花括号间使用空格
endOfLine: auto # 换行符：auto
printWidth: 80 # 每行最大字符数
singleQuote: false # 使用双引号
semi: true # 使用分号
tabWidth: 2 # tab宽度：2个空格
trailingComma: all # 尾随逗号
useTabs: false # 使用空格代替tab
