name: 新功能
description: 提交一个新功能请求。
#title: 你的标题
labels:
  - enhancement
  - question
assignees:
  - BTMuli
body:
  - type: markdown
    attributes:
      value: |
        感谢您的提交，至少填写下方带红色星花标记的部分。
  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 在此详细描述你想新增的功能。
      placeholder: 在此输入 Markdown 文本。
      #value:
    validations:
      required: true
  - type: textarea
    id: git-log
    attributes:
      label: 当前提交
      description: 将命令 `git log -1` 的输出粘贴在此处。
      render: Text
      placeholder: 在粘贴命令输出，将被转化为代码块。
      #value:
    validations:
      required: true
