# 配置文件
Commands:
  # Markdown
  mmd:
    enable: true
    name: markdown
    default:
      author: '目棃'
      filename: 'README'
      description: '说明文档'
    typora:
      enable: true
      path: 'E:\\SoftWares\\Typora\\Typora.exe'
  # SubCommand
  ncm:
    enable: true
    name: subCommand
    # Dev model
    dev:
      enable: false
      userInfoPath: './test/upInfo_33009606.json'
