Commands:
    mmd:
        enable: true
        name: markdown
        default:
            author: 目棃
            filename: README
            description: 说明文档
        typora:
            enable: true
            path: 'E:\\SoftWares\\Typora\\Typora.exe'
    tpl:
        enable: false
        name: template
    ncm:
        enable: true
        name: subCommand
