# 配置文件
Commands:
  # Markdown
  mmd:
    enable: true
    name: markdown
    default:
      author: '目棃'
      filename: 'README'
      description: '说明文档'
    typora:
      enable: true
      path: 'E:\\SoftWares\\Typora\\Typora.exe'
  # SubCommand
  ncm:
    enable: true
    name: subCommand
  # Bilibili Spider
  bili:
    enable: true
    name: bilibili
    api:
      user:
        # 基本信息
        info:
          auth: false
          url: 'https://api.bilibili.com/x/space/acc/info?mid={}'
        # 粉丝 关注
        relation:
          auth: false
          url: 'https://api.bilibili.com/x/relation/stat?vmid={}'
        # 播放数 浏览数 authed
        upstat:
          auth: true
          url: 'https://api.bilibili.com/x/space/upstat?mid={}'
      video:

    # Dev model
    dev:
      enable: true
      userInfoPath: './test/upInfo_33009606.json'
